<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>EVA_ECS.Chat.Contracts</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>EVA_ECS.Chat.Contracts</PackageId>
    <Version>1.0.1</Version>
    <Authors>EVA_ECS Team</Authors>
    <Description>Shared Contracts, DTOs und RabbitMQ-Events for the Chat-System</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
