name: Publish NuGet Package

on:
    push:
        branches: ["main"]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET 8
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            - name: Pack NuGet Package
              run: dotnet pack EVA-ECS.Chat.Contracts/EVA-ECS.Chat.Contracts.csproj -c Release

            - name: Push to GitHub Packages
              run: dotnet nuget push "bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/EVA-ECS/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
